package com.capgemini.studentexception.tests;

import static org.junit.Assert.assertNotNull;

import org.junit.Test;

import com.capgemini.studentexception.exception.StudentException;
import com.capgemini.studentexception.main.Student;

public class StudentTest {

	@Test
	public void testToCheckStudentObjectWithDefaultconstructor() {
		Student student = new Student();
		assertNotNull(student);
	}

	@Test(expected = StudentException.class)
	public void testToCheckAgeisNotWithinRange() {
		Student student = new Student(78, "Lahari", 22, "Btech");

	}

	@Test(expected = StudentException.class)
	public void testToCheckAgeisWithinRange() {
		Student expected = new Student(79, "Narra", 20, "Btech");

	}

	@Test(expected = StudentException.class)
	public void testToCheckNameisNotValidException() {
		Student student = new Student(78, "L@*ari", 22, "Btech");

	}

	@Test(expected = StudentException.class)
	public void testToCheckNameIsValidException() {
		Student expected = new Student(78, "Lahari", 22, "Btech");

	}

}